spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school_message_tool?characterEncoding=utf-8
    username: root
    password: xjl1994920
  jpa:
    show-sql: true
#  data:
#      mongodb:
#        uri: mongodb://192.168.0.114:27017/school_message_tool