server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.17.0.3:3306/school_message_tool?characterEncoding=utf-8
    username: root
    password: xjl1994920
  jpa:
    show-sql: false
#  data:
#    mongodb:
#      uri: mongodb://45.77.159.109:27017/school_message_tool